### ISSUE TITLE
MIssing / incorrect information

### ISSUE THREAD

**Issue by Ndolam** [cheusov/dictd#12]
README says 
"INSTALLATION
============

    Please see the file INSTALL in this directory"

There is no such file.

In doc/INSTALL it says to run configure.  There is no configure.

I like puzzles as much as the next guy, but I bet there are people out there who don't.   :-)

**Comment by cheusov** [comment]
I'm changing a build system from autoshit to mk-configure. It's still in progress.

**Comment by Ndolam** [comment]
OK, thanks for the info.
